source 'https://rubygems.org'

gem 'capybara'
gem 'pry'
gem 'cucumber', '3.1.2'
gem 'rspec'
gem 'selenium-webdriver'
gem 'webdrivers'
gem 'site_prism'
gem 'cpf_faker'
gem 'faker'
gem 'allure-cucumber', '2.13.3'
gem 'test-unit'
gem 'yard'
gem 'yard-cucumber'
gem 'rspec'
gem 'ffi'
gem 'pry'
gem 'rake'
gem 'redcarpet'
gem 'rspec-expectations'
gem 'clipboard'
gem 'rubocop', require: false
gem 'dbi'
#gem 'ruby-oci8'